### ISSUE TITLE
Feedback on your wiki

### ISSUE THREAD

**Issue by scharffc** [paceuniversity/CS3892016team2#1]
@vinacovre @christianobrien @Ryan-Faranda 

Please review your wiki.

Additional Information 
Lots of the links are not working

Put the link to our Slack team.

Tools seem unfinished.

**Comment by viniciuscovre** [comment]
@scharffc Hello professor!

What links are not working? I've tested all of them in an anonymous window of Chrome and they all worked.

**Comment by scharffc** [comment]
@vinacovre

It sounds that there are syntax errors
[image: Inline image 1]

**Comment by viniciuscovre** [comment]
@scharffc 
Items corrected. Thank you!
