### ISSUE TITLE
Group member cannot be assigned to an issue

### ISSUE THREAD

**Issue by viniciuscovre** [paceuniversity/CS3892016team2#17]
The team member Michael Rodriguez (https://github.com/msr23) cannot be assigned to any issue. Please add him to our Git repo.

**Comment by scharffc** [comment]
@christianobrien 

Can you help with this issue? Why is Michael not on the wiki? What is his username?

**Comment by viniciuscovre** [comment]
@scharffc 

Michael's username is @msr23

**Comment by viniciuscovre** [comment]
@dhruv857 

Can you please add @msr23 to our team? This way we can assign him an issue.

**Comment by dhruv857** [comment]
@vinacovre I had sent him the invitation along with others on the team. Tell him to check his spam/ archived.

**Comment by msr23** [comment]
Hey Dhruvil,
I was able to find the invitation to slack it was in my spam folder unfortunately. So i joined the slack but am not in my teams designated chat and I'm not sure how that relates to the GitHub issue of me not being able to work on the page. Please let me know if you know what the problem may be. Sorry for the inconvenience but thanks for the help :+1:
