### ISSUE TITLE
Sprint goal

### ISSUE THREAD

**Issue by scharffc** [paceuniversity/CS3892016team2#19]
@vinacovre @christianobrien @Ryan-Faranda 

Great job!

You can add  a label for each task to show that they are in Sprint 1.

**Comment by scharffc** [comment]
@vinacovre @christianobrien @Ryan-Faranda

Also add comments to the issues / tasks during the sprint for time estimates and such that we know what is hapenning.

**Comment by viniciuscovre** [comment]
@scharffc 

Thank you!

We are using milestones for the sprints. But I also added labels for the Sprint 1 as you asked.
